using System.IO.Compression;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using TextMateSharp.Internal.Grammars.Reader;
using TextMateSharp.Internal.Types;

namespace Huskui.Avalonia.Code.Highlighting;

/// <summary>
///     Language catalog and gzip-packed TextMate grammars embedded in this assembly. Generated by
///     tools/Huskui.GrammarExtractor from the TextMateSharp.Grammars snapshot — see
///     docs/grammar-assets.md for the source snapshot and the update procedure.
/// </summary>
internal sealed partial class GrammarManifest
{
    private const string ResourcePrefix = "Huskui.Grammars.";
    private const string ManifestResourceName = "Huskui.Grammars.manifest.json";

    private static readonly Assembly Assembly = typeof(GrammarManifest).Assembly;
    private static GrammarManifest? _instance;

    private readonly Dictionary<string, string> _extensionScopes;

    private GrammarManifest(Snapshot snapshot)
    {
        Languages = snapshot.Languages;
        Grammars = snapshot.Grammars;
        _extensionScopes = new Dictionary<string, string>(
            snapshot.ExtensionScopes,
            StringComparer.OrdinalIgnoreCase
        );
    }

    public static GrammarManifest Instance => _instance ??= Load();

    public Dictionary<string, string> Grammars { get; }

    public List<Language> Languages { get; }

    public string? GetScopeByExtension(string extension) =>
        _extensionScopes.TryGetValue(extension, out var scope) ? scope : null;

    public IRawGrammar? GetGrammar(string scopeName)
    {
        if (!Grammars.TryGetValue(scopeName, out var resourceName))
            return null;

        using var stream =
            Assembly.GetManifestResourceStream(ResourcePrefix + resourceName)
            ?? throw new InvalidOperationException($"Embedded grammar {resourceName} is missing.");
        using var gzip = new GZipStream(stream, CompressionMode.Decompress);
        using var reader = new StreamReader(gzip);
        return GrammarReader.ReadGrammarSync(reader);
    }

    private static GrammarManifest Load()
    {
        using var stream =
            Assembly.GetManifestResourceStream(ManifestResourceName)
            ?? throw new InvalidOperationException("Embedded grammar manifest is missing.");
        var snapshot = JsonSerializer.Deserialize(
                stream,
                SnapshotContext.Default.Snapshot
            )
            ?? throw new InvalidOperationException("Embedded grammar manifest is malformed.");
        return new GrammarManifest(snapshot);
    }

    internal sealed record Language(string Id, List<string>? Aliases, string? Scope);

    internal sealed record Snapshot(
        List<Language> Languages,
        Dictionary<string, string> Grammars,
        Dictionary<string, string> ExtensionScopes
    );

    [JsonSourceGenerationOptions(PropertyNameCaseInsensitive = true)]
    [JsonSerializable(typeof(Snapshot))]
    internal partial class SnapshotContext : JsonSerializerContext;
}
